CC = g++
CFLAGS = -Wall
PROG = 201201045_Assignment1

SRCS = 201201045_Assignment1.cpp
LIBS = -lglut -lGL -lGLU

all: $(PROG)

$(PROG):	$(SRCS)
	$(CC) $(CFLAGS) -o $(PROG) $(SRCS) $(LIBS)

clean:
	rm -f $(PROG)
